### ISSUE TITLE
Approval on dapp asks for wrong spender

### ISSUE THREAD

**Issue by dynsky** [manifoldfinance/staking#30]
in deposit section after clicking complete staking dapp prompts for approving XFOLD with manifold contract address as spender which is wrong. domodao address should be the spender. unstaking works because spender address for XFOLD approval in withdraw section is correct but users are still losing gas costs due to meaningless transaction in deposit section.

instead of resolving it i suggest deleting XFOLD approval from deposit section, there is no need for it if its in withdraw section already.

**Comment by sambacha** [comment]
Thanks will get this fixed asap

**Comment by sambacha** [comment]
this is resolved in the latest release 

https://github.com/manifoldfinance/staking/releases/tag/v0.8.1

confirmed behavior via transaction:
https://etherscan.io/tx/0xbe90132155f6e198af02cfe58ca98981888ecdc39514b2ef5e025b467f4e6ea7

**Comment by dynsky** [comment]
@sambacha issue is still present
![depositxfold](https://user-images.githubusercontent.com/96447749/147873620-52fd0b0e-0773-4838-ac35-530ba7d657c3.png)

**Comment by dynsky** [comment]
@sambacha issue is still present
![depositxfold](https://user-images.githubusercontent.com/96447749/147873655-44a211ce-e829-4595-8142-c19055d66355.png)

**Comment by sambacha** [comment]
> @sambacha issue is still present ![depositxfold](https://user-images.githubusercontent.com/96447749/147873655-44a211ce-e829-4595-8142-c19055d66355.png)

Did you add the token id's using the button on the dapp?

**Comment by dynsky** [comment]
no, i added it manually but i did it now using button and nothing changed

**Comment by sambacha** [comment]
> @sambacha issue is still present ![depositxfold](https://user-images.githubusercontent.com/96447749/147873655-44a211ce-e829-4595-8142-c19055d66355.png)



> no, i added it manually but i did it now using button and issue is still present

You are trying to **deposit** correct? We are re-working our state management , this address has already authorized the DictatorDAO/DomoDAO contract correct?

**Comment by dynsky** [comment]
yes and yes

**Comment by sambacha** [comment]
@dynsky we will be tracking this issue here https://github.com/manifoldfinance/staking/issues/35

Thanks so much for reporting this, will make sure you get a bug bounty ser

**Comment by sambacha** [comment]
@dynsky  please let us know if you find any other issues, and whats a good address to send some DAI ?

see https://github.com/manifoldfinance/staking/releases/tag/v0.8.3

**Comment by dynsky** [comment]
@sambacha thanks, 0x4A358BCCe623c2a0994C58331d460c7dA9DE78aB
current issue occurs after connecting wallet 
![currentissue](https://user-images.githubusercontent.com/96447749/147878624-ee06c802-375e-4965-97ad-cc1c13ee9d9c.png)
![browser console](https://user-images.githubusercontent.com/96447749/147878628-b4f9f551-e523-4634-952a-40c63b30ede3.png)

**Comment by sambacha** [comment]
> @sambacha thanks, 0x4A358BCCe623c2a0994C58331d460c7dA9DE78aB current issue occurs after connecting wallet ![currentissue](https://user-images.githubusercontent.com/96447749/147878624-ee06c802-375e-4965-97ad-cc1c13ee9d9c.png) ![browser console](https://user-images.githubusercontent.com/96447749/147878628-b4f9f551-e523-4634-952a-40c63b30ede3.png)

what browser is this?

**Comment by sambacha** [comment]
https://etherscan.io/tx/0xe44aee512193d99743c6003255a3bc4bcf72d52425388037c87d8b279e396ca5

**Comment by dynsky** [comment]
firefox 95.0.2, other user on brave browser also has this issue

**Comment by sambacha** [comment]
> firefox 95.0.2, other user on brave browser also has this issue

this should fix it, https://github.com/manifoldfinance/staking/runs/4684666056?check_suite_focus=true 

reverting server side rendering feature , it will be deployed in a few minutes

**Comment by dynsky** [comment]
@sambacha 
![iss](https://user-images.githubusercontent.com/96447749/147881977-a2ebdc92-fd35-44cd-8bba-f3252c503d38.png)

**Comment by dynsky** [comment]
@sambacha after refreshing site, only `sendRemoveListener on closed conduit` is produced again
![bugas](https://user-images.githubusercontent.com/96447749/147882988-31c74618-64d7-44a9-9d1d-3324f4b159d3.png)

**Comment by dynsky** [comment]
@sambacha after refreshing site, `only sendRemoveListener on closed conduit` is produced again
![bugas](https://user-images.githubusercontent.com/96447749/147883113-7f2c95ab-8c34-4d7f-99d1-fb6cffdcbcf2.png)

**Comment by sambacha** [comment]
should be fixed now.

**Comment by dynsky** [comment]
@sambacha issue is still present, users are reporting it
cant that one wrong approval of xfold with manifold contract address as spender be deleted? you wanted to solve it by rewriting state management, but this isn't faulty state checking, just excess transaction that is meaningless
